@startuml

!include access_login.puml
!include change_user_role.puml
!include check.puml
!include check_login.puml
!include complete_task.puml
!include create_chat.puml
!include create_group_chat.puml
!include create_order.puml
!include create_report.puml
!include create_user.puml
!include crud_bd.puml
!include forward_msg.puml
!include log_doc.puml
!include logout.puml
!include look_msg.puml
!include parse_order_info.puml
!include receive_msg.puml
!include receive_user_id.puml
!include response_msg.puml
!include safe_doc.puml
!include select_chat.puml
!include select_item.puml
!include select_msg.puml
'!include select_order.puml
!include select_stuff.puml
!include send_msg.puml
!include show_checklists.puml
!include show_error.puml
!include show_msg.puml
!include update_msg.puml
!include use_case_login.puml

@enduml