@startuml
frame "Deployment NWchat Web Application        " {
    node "<<divice>> \n :AplicationServer \n {OS=Solaris}" as back_end {
        node "<<JSP server>> \n Tomcat" as jsp{
            artifact "<<artifact>> \n NWchat.war" as war
        }
        node "<<DB>> \n PostgreSQL" as bd{
            database "NWchatDB"
        }
     }
    jsp -- bd: <<JDBC>>


    node "<<device>> \n :ClientDevices" as client {
        component "Web Browser"
    }

    client -- back_end: <<protocol>> \n HTTP/HTTPS v1.1

}
@enduml