@startuml
'
'
' Implementation view
'
'

actor user

participant "web page" as wp
participant Controller as c
participant "Security System" as sec
participant "Data Base" as db


user -> wp : push button 'logout'
wp -> c : http_get("/logout")
c -> sec : getAuthorizationUser()
alt user authorized
    sec -> c : response current user
    c -> sec : logout(current user)
    sec -> db : removeToken(user)
    alt successful case
        sec <- db : removed
        c <- sec : ok
        wp <- c : redirect
        user <- wp : display
    else failure
        sec <- db : fault
        c <- sec : exception
    end

    sec -> c : response null

end

@enduml
