@startuml
'
'
' Implementation view
'
'

actor user

participant "web page" as wp
participant Controller as c
participant "Security System" as sec
participant "Data Base" as db


user -> wp : push button 'logout'
wp -> c : get("/logout")
c -> sec : getAuthorizationUser()
sec -> c : response
c -> sec : logout(current user)
alt successful case
    c <- sec : ok
    c -> db : Log logout successful
    c <- db : write
else failure
    c <- sec : exception
    c -> db : Log error
    c <- db : write
end

wp <- c : redirect
user <- wp
@enduml
