@startuml
'
'
' Use case View
'
'

actor user

participant "message form" as wp
participant server as s


user -> wp : type text and push button
loop message not delivered
    wp -> s : send message
    alt successful case
        wp <- s : message delivered
    else failure
        wp <- s : message not delivered

    end
end
user <- wp : display

@enduml
