@startuml
package com.nwchat{
    namespace Configuration{
    }
    namespace Listener{
    }
    namespace Model{
    }

    namespace Repository{
    }

    namespace Service{
    }

    namespace Controller{
    }
    Listener ..> Model : <import>
    Service ..> Model : <import>
    Controller ..> Model : <import>
    Repository ..> Model : <import>
    Controller ..> Repository : <import>
    Controller ..> Service : <import>
}

package resources{
    namespace static{
        namespace css{
        }
        namespace js{
        }
    }

    namespace Templates{
    }

    Templates ..> static.js : <import>
    Templates ..> static.css : <import>
}
Templates <. Controller : <use>
@enduml