@startuml
[*] -> СозданиеОтчета
СозданиеОтчета --> Отменен:[Создание отчета \n отменено]
Отменен --> [*]
СозданиеОтчета --> РедактированиеОтчета:[Некоторые элементы \n не заполнены] \n Processed
РедактированиеОтчета --> ОтчетЗакончен:[Все элементы \n отчета заполнены]
СозданиеОтчета --> ОтчетЗакончен:[Элементы отчета \n заполнены]
ОтчетЗакончен --> ОтчетОтправлен
ОтчетЗакончен --> ОтчетСохранен:[Сохранить \n отчет]
РедактированиеОтчета --> ОтчетСохранен:[Сохранить \n отчет]
ОтчетСохранен --> РедактированиеОтчета:[Открытие \n документа]
ОтчетОтправлен --> ОтчетОтправлен:[Отчет не доставлен \n до пользователя]
ОтчетОтправлен --> ОтчетДоставлен:[Отчет доставлен]
ОтчетДоставлен --> [*]
@enduml