@startuml

[*] --> ИзменениеОбъектаВРесурсах
state ИзменениеОбъектаВРесурсах {

}

state ИзменениеКлассаСервлет {
    state "Method and controller is selected    \n for creating chat " as ИзменениеВКонтройлере
    [*] -> ИзменениеВКонтройлере
    state "Выбор модели" as ИзменениеКлассаСервлетБЛ
    ИзменениеВКонтройлере --> ИзменениеКлассаСервлетБЛ: <<ChatModel>>
    ИзменениеКлассаСервлетБЛ --> ФормированиеОтвета:<<ModelAndView>>
    ФормированиеОтвета -> [*]
}
ИзменениеОбъектаВРесурсах --> ИзменениеКлассаСервлет :HTTP/HTTPS method


state DB {
    state "Data is received  " as data_recive
    state "Data is saved" as data_save
    [*] --> data_recive
    data_recive --> data_save
    data_save --> [*]
}
ИзменениеКлассаСервлетБЛ -> DB :JDBC
DB -> ИзменениеКлассаСервлетБЛ :JDBC

ИзменениеКлассаСервлет -left-> НоваяСтраница : <<HTML page>>
НоваяСтраница --> [*]

state "Waiting for click \n button 'Create chat'    " as ИзменениеОбъектаВРесурсах:
state "Servlet Conteiner Spring \n Waiting for request" as ИзменениеКлассаСервлет
state "Execution of \n Business logic " as ИзменениеКлассаСервлетБЛ
state "Formation of response for client     " as ФормированиеОтвета
state "New page is displayed    " as НоваяСтраница

@enduml