@startuml
[*] --> CreateOrderButtonIsPress
CreateOrderButtonIsPress --> CreateOrderFormIsOpen: [Система открывает форму \n 'Создание отчета']
CreateOrderFormIsOpen --> ChangeFormFills:[User заполняет поля формы \n 'Создание отчета']





CreateOrderButtonIsPress: Нажата кнопка 'Создать отчет'
CreateOrderFormIsOpen: Форма 'Создание отчета' \n открыта у User на экране
ChangeFormFills: User вносит изменения в \n активыне поля формы
@enduml