@startuml

!includesub ../actor/all.puml!BASIC

!include low/all.puml

'user
!includesub forward_msg.puml!BASIC
!includesub response_msg.puml!BASIC
!includesub receive_msg.puml!BASIC
!includesub look_msg.puml!BASIC
!includesub login.puml!BASIC
!includesub logout.puml!BASIC
!includesub send_msg.puml!BASIC
!includesub check_privelegii.puml!BASIC
!includesub create_chat.puml!BASIC
!includesub complete_item_checklist.puml!BASIC

'lk
!includesub create_order.puml!BASIC
!includesub create_user.puml!BASIC
!includesub change_user_role.puml!BASIC


'manager
!includesub create_report.puml!BASIC
!includesub create_group_chat.puml!BASIC
!includesub select_chat.puml!BASIC

'other
!includesub select_stuff.puml!BASIC
!includesub select_item_check_list.puml!BASIC


@enduml