@startuml
!startsub BASIC
!include ../actor/user.puml
(Проверка прав доступа) as check

user - (check)
(Запрос в базу данных) as crud_bd
(Получить идентификатор пользователя) as receive_id
(check) ..> (receive_id):<<include>>
(check) ..> (crud_bd):<<include>>
(check) ..> (Предоставить функционала)
!endsub
@enduml