@startuml
!include ../actor/user.puml
!startsub BASIC

usecase (Проверка прав доступа) as check
usecase (Запрос в базу данных) as crud_bd
usecase (Получить идентификатор пользователя) as receive_user_id

user - (check)
check ..> receive_user_id : <<include>>
check ..> crud_bd : <<include>>

!endsub
@enduml