@startuml
!startsub BASIC
!import ../actor/lk.puml
usecase (Создать приказ) as UC1_order
usecase (Проверить \n права доступа) as UC2_order
usecase (Выбрать \n людей из списка) as UC3_order
usecase (Выбрать  пункты \n чеклиста) as UC4_order
usecase (Сохранить документ) as UC5_order
usecase (CRUD DB) as UC6_order

lk - UC1_order

UC1_order .> UC2_order:<<include>>
UC1_order ..> UC3_order:<<include>>
UC1_order ..> UC4_order:<<include>>
UC1_order ...> UC5_order:<<include>>
UC5_order .> UC6_order:<<include>>
!endsub

@enduml