@startuml
!include ../actor/manager.puml
!startsub BASIC

!include low/create_group_chat.puml
!include low/check.puml
!include low/select_stuff.puml
!include low/select_item.puml
!include low/crud_bd.puml
!include low/create_chat.puml

manager -- create_group_chat
create_group_chat ..> check : <include>
create_group_chat ..> select_stuff : <include>
create_group_chat ..> select_item : <include>
create_group_chat ..> create_chat : <include>
create_chat ..> crud_bd : <include>

!endsub
@enduml