@startuml
!include ../actor/manager.puml
!startsub BASIC
!include low/create_report.puml
!include low/check.puml
!include low/crud_bd.puml
!include low/select_chat.puml

manager -- create_report
create_report ..> check : <include>
create_report ..> select_chat : <include>
create_report ..> crud_bd : <include>

!endsub
@enduml