@startuml
!include ../actor/user.puml
!startsub BASIC

!include low/create_chat.puml
!include low/check.puml
!include low/select_stuff.puml
!include low/crud_bd.puml

user -- create_chat
create_chat ..> check : <include>
create_chat ..> select_stuff : <include>
create_chat ..> crud_bd : <include>

!endsub
@enduml