@startuml
!include ../actor/manager.puml
!include ../actor/user.puml

rectangle {
!include low/create_chat.puml
!include low/check.puml
!include low/select_stuff.puml
!include low/crud_bd.puml
!include low/create_group_chat.puml
!include low/select_item.puml
!include low/create_chat.puml
}
user -- create_chat

!startsub BASIC
create_chat ..> check : <include>
create_chat ..> select_stuff : <include>
create_chat ..> crud_bd : <include>

manager -- create_group_chat
create_group_chat ..> select_item : <include>
create_group_chat ..> create_chat : <include>
!endsub

manager -> user
@enduml