@startuml
!startsub BASIC
!import ../actor/lk.puml
usecase (Создать приказ) as UC1
usecase (Проверить \n права доступа) as UC2
usecase (Выбрать \n людей из списка) as UC3
usecase (Выбрать  пункты \n чеклиста) as UC4
usecase (Сохранить документ) as UC5
usecase (CRUD DB) as UC6

lk - UC1

UC1 .> UC2:<<include>>
UC1 ..> UC3:<<include>>
UC1 ..> UC4:<<include>>
UC1 ...> UC5:<<include>>
UC5 .> UC6:<<include>>
!endsub

@enduml