@startuml
!include ../actor/user.puml
!startsub BASIC

!include low/forward_msg.puml
!include low/crud_bd.puml
!include low/select_msg.puml
!include low/select_chat.puml

user -- forward_msg
forward_msg ..> crud_bd : <include>
forward_msg ..> select_msg : <include>
forward_msg ..> select_chat : <include>

!endsub
@enduml