@startuml
!startsub BASIC

usecase (Проверить \n права доступа) as access
usecase (Выбрать \n людей из списка) as select_staff
usecase (Выбрать  пункты \n чеклиста) as select_item
usecase (CRUD DB) as crud_db

!endsub
@enduml