@startuml
!include ../actor/user.puml
rectangle {
!include low/logout.puml
!include low/log_doc.puml
!include low/receive_user_id.puml
}

!startsub BASIC
user -- logout
logout ..> log_doc : <include>
logout ..> receive_user_id: <include>
!endsub
@enduml