@startuml
!include ../actor/user.puml

rectangle {
!include low/look_msg.puml
!include low/show_msg.puml
!include low/crud_bd.puml
}

!startsub BASIC
user -- look_msg
look_msg ..> crud_bd : <include>
look_msg ..> show_msg : <include>
!endsub
@enduml