@startuml
!include ../actor/user.puml
!startsub BASIC

!include low/look_msg.puml
!include low/show_msg.puml
!include low/crud_bd.puml

user -- look_msg
look_msg ..> crud_bd : <include>
look_msg ..> show_msg : <include>

!endsub
@enduml