@startuml
!include ../actor/user.puml
!startsub BASIC

(Получить сообщение ) as look_msg
(Запрос в базу данных) as crud_bd

user -- (look_msg)
(look_msg) ..> (crud_bd):<<include>>
(look_msg) ..> (Показать сообщения в списке):<include>>
!endsub
@enduml@enduml