@startuml
!startsub BASIC
!include ../actor/user.puml
(Посмотреть сообщение ) as lookMsg

user - (lookMsg)

(Запрос в базу данных) as crud_bd
(lookMsg) ..> (crud_bd):<include>
(lookMsg) ..> (Показать сообщение):<<include>>
!endsub
@enduml