@startuml
!include ../actor/lk.puml
!include ../actor/manager.puml
!startsub BASIC

!include low/select_stuff.puml
!include low/crud_bd.puml

lk -- select_stuff
manager -- select_stuff
select_stuff ..> crud_bd :<include>

!endsub
@enduml

