@startuml
!include ../actor/lk.puml
!include ../actor/manager.puml
!startsub BASIC

(Выбрать людей из списка ) as select_stuff

lk --(select_stuff)
manager - (select_stuff)

(select_stuff) ..>(Поиск идентификатора пользователя в БД ):<<include>>

!endsub
@enduml

