@startuml
!include ../actor/user.puml

rectangle "List People" as lp
rectangle Server as ser
rectangle "List item" as item

user -> lp : 1: нажать на кнопку 'Выбрать пользователя'
lp -> ser : 2: Получить список пользователей
lp <- ser : 3: Response()
lp --> item : 4: create()
item -> user : 5: отобразить
user -> item : 6: Выбрать Васю



@enduml