@startuml
!include ../actor/user.puml

rectangle ListPeople
rectangle Server

user -> ListPeople : 1: Выбрать Васю
ListPeople -> Server : 2: Получить список пользователей
ListPeople <- Server : 3: Response()



@enduml