@startuml
!include ../actor/user.puml

rectangle "WebPage" as addManger
rectangle Server
user ->addManger:1: post('get all user')

addManger-> Server: request()
addManger<-- Server: response()
@enduml