@startuml
'Проверка прав доступа'




frame "Проверка прав доступа" {
!include ../actor/user.puml

artifact "successful: user.authorization == true" as suc

rectangle WebPage as sys
rectangle DataBase as db
rectangle Controller as ctr
rectangle "Security System" as sc

}

user -> sys : 1: Button.click()
sys -> ctr : 2: Get()
sc <--ctr: 3: CheckAuthorization()
ctr -> db : 4: [successful] selectRole(user)


@enduml