@startuml
'Просмотр сообщений'
frame "Просмотр сообщений"{
!include ../actor/user.puml

rectangle "ChatMessageRepository" as messageRep
rectangle "List<ChatMessageEntity>" as listMessage
rectangle "Controller"
rectangle "Dispatcher"
}
user ->Dispatcher: "1:http method get: /messages/"
Dispatcher -> Controller :2: index()
Controller --> messageRep :3:findAllById()
messageRep --> listMessage:4: showMessage()

@enduml