@startuml
'Получение новых сообщений'
frame "Получение новых сообщений"{
!include ../actor/time.puml


rectangle "ChatEntity"
rectangle "ChatMessageEntity"
}
time ->ChatEntity: "1. getMessageAfter(data)"
ChatEntity --> ChatMessageEntity :2. after(date)


@enduml