@startuml
frame "Выбрать людей из списка"{
!include ../actor/user.puml
'Выбрать людей из списка'

rectangle "UserRepository" as userRep
rectangle "List<User>" as listUser
rectangle "Controller"
rectangle "Dispatcher"
}

user -> Dispatcher :  "1:http method get: /user/"
Dispatcher -> Controller : 2: index()
Controller --> userRep: 3:findAllById()
userRep -> listUser : 4: Create()





@enduml