@startuml
(*) --> ==R1==
partition Resources {
  ==R1== --> "Управляющий нажимает кнопку 'отчет'"
  --> "Показать страницу создать отчет"

}

partition com.nwchat {
    partition controller {
    if " " then
    note right:Есть активные приказы?
    }
}

partition Resources {
    -up-> [Yes] "Управляющий выбирает \n из списка нужный приказ "
}

partition com.nwchat {
 partition Service {
 --> "Система заполняет форму 'отчет'\n по выбранному приказу"
 }
}

partition Resources {
    --> "Управляющий проверяет \n корректность заполнения"
    --> "Управляющий нажимает \n кнопку 'отправить'"
}

partition com.nwchat {
    partition controller {
    if " " then
    note left: Система успешно \n обработала отправку?
    }
}

partition Resources {
    -left-> [Yes] "Управляющий видит сообщение \n 'Отчет отправлен'"
    else
    -up-> [No] "Управляющий видит сообщение \n 'Отчет не отправлен'"
}

"Управляющий видит сообщение \n 'Отчет отправлен'" --> (*)

partition com.nwchat {
    partition Repository {
        "Управляющий видит сообщение \n 'Отчет не отправлен'" --> "Созданный отчет \n сохраняется в DB "
    }
}
--> (*)
endif

else
--> [No] (*)
endif


@enduml