@startuml

(*) --> "User открывает страницу NWchat" as init
if "[User авторизирован?(проверка cookies)]" then
  -left->[Yes] "Авторизировать
  User"
  --> "Показать домашнию страницу" as home
  --> (*)
  else
    -->[No] "Показать страницу
    авторизации"
   --> "User заполняет
    UserLogin и Password" as fills
   --> "User нажимает 'Log in'"
   --> "Сервер верифицирует
    UserLogin и Password"
   if "[Данные коректны?]" then
    -->[Yes] home
   else
    -->[No] "Показать сообщение об ошибке"
    -->fills
endif
@enduml