@startuml

(*) --> "User открывает страницу NWchat" as init
if "[есть ли идентификатор пользователя?(cookies)]" then
  -left->[Yes] "получить идентификатор пользователя"
  if "[проверка срока годности и\nидентичности с данными в бд]" then
    -> [Yes] "Показать домашнию страницу" as home
    --> (*)
  else
    -> [No] "Показать страницу\n входа в систему" as loginP
  endif
else
   -->[No] loginP
   --> "User заполняет\n UserLogin и Password,\n нажимает 'Log in'" as fills
   --> "Аутентификацию\n пользователя по\n UserLogin и Password"
   if "[Данные совпадают с данными в бд?]" then
    -->[Yes] home
   else
    -->[No] "Показать сообщение об ошибке"
    -->fills
endif
@enduml